### PR TITLE
Geo raster mini rasters

### PR DESCRIPTION
**Pull request by ozak**
@perrygeo Matthew I have changed the file so as to allow an option to use GeoRasters as output if ``georasters`` is installed on the system . GeoRasters have a function to write GeoTiffs. They should make life in general easier for the user...let me know if you want to incorporate this version.

### CODE REVIEW

**Comment by perrygeo** [comment]
This needs to be rebased or rewritten for the new rasterio implementation.

**Comment by ozak** [comment]
Hi Matthew. So you mean, include the pieces of code that refer to GeoRasters in the new master ``rasterstats/main.py``?

**Comment by perrygeo** [comment]
Yes, I just pushed some recent changes to use `rasterio` instead of `osgeo.gdal` and it involved some minor refactoring, enough that I can no longer cleanly merge this PR. No big deal, just wanted to let you know..

**Comment by ozak** [comment]
Ok. I am putting the stuff together again...it was just a couple of extra lines, so should be easy to include.

**Pull request closed without merging**
